name: Build site with Hugo
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string.
    # Run every day at 12:00AM.
    - cron:  '0 0 * * *'
jobs:
  buildSite:
    env:
      GOPATH: ${{ github.workspace }}
    name: Install deps and build site
    runs-on: ubuntu-latest
    steps:
      - name: Print all env vars
        run: |
          echo "GITHUB_REF=${GITHUB_REF}"
          echo "GITHUB_SHA=${GITHUB_SHA}"
          echo "GITHUB_EVENT_PATH=${GITHUB_EVENT_PATH}"
      - name: Print event json
        run: |
          cat "${GITHUB_EVENT_PATH}" | jq -r .
